name: Node.js Package Pull Request

on: 
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: 12
      - run: npm ci
      - run: npm test mocktest
      - run: npm run build
